### ISSUE TITLE
Interested in contributions?

### ISSUE THREAD

**Issue by haliphax** [phonicmouse/SharpPaste#1]
I took **SharpPaste** and ran with it yesterday for an internal project, and I've managed to make some useful additions to the codebase:

- Paste expiration (1 hour, 1 day, 1 week, and a "burn after reading" option)
  - "Burn after reading" will destroy the paste after it is viewed (or after an hour, whichever comes first), ensuring it can only be viewed once
- Integrated [Hangfire](http://hangfire.io) in order to kick off a scheduled job for cleaning expired pastes
- The ability to protect the `/paste/list` URL with an authorization token (e.g., `/paste/list/{token}`)

Are you interested in receiving contributions to this project, or is it more of just a hobby/experiment of your own?

**Comment by phonicmouse** [comment]
Hi @haliphax ,

First of All, Thank You for contacting me. 
I'm really interested to receive contributions, and your improvements were in my todo list, so this is awesome.
Can you create a pull request with the new code so I can see what you changed and then merge it to the master branch?

Thank You

**Comment by haliphax** [comment]
Absolutely. I'll clean it up so the new features can be controlled through configuration and get a PR sent.

Cheers!

**Comment by phonicmouse** [comment]
That would be fantastic. Thanks!

**Comment by phonicmouse** [comment]
Any news @haliphax ?

**Comment by haliphax** [comment]
I've been off work and busy with the holidays for the past week. I did manage to pull all the code down to my laptop, and I got a custom `web.config` section built and tested. I still need to get it setup to where the expiration options are configurable, and then it will be good to go.

**Comment by phonicmouse** [comment]
That's good. Tell me when you are ready to pull. Look at the new source, i made some changes...if they can help you.
I'll wait for your source, in the meanwhile, happy new year!

P.S.: Here's my [email](mailto:phonicmouse@gmail.com), if you need anything i have it on my smartphone so i can reply to you at any time.

**Comment by haliphax** [comment]
Oh, man. Life got away from me there for a while. I hope to pull down the new source and get this knocked out in the coming week. Work has just been insane lately. :P

**Comment by phonicmouse** [comment]
I imagined...if you need or if you want to make other changes in the source you can.
Thank You Anyway 😃

**Comment by phonicmouse** [comment]
Hi #haliphax , any news?

**Comment by phonicmouse** [comment]
I'm continuing to ask just because those features that you added would be very useful ;)

**Comment by phonicmouse** [comment]
Hi @haliphax, I haven't heard about you for a long time, how is proceeding your project?

**Comment by haliphax** [comment]
They squashed my idea to use this for work. I do still plan on working on it at home, but I need to get the code off of my laptop at the office. I'll see if I can knock it out this weekend or an upcoming evening. Sorry for the delay! :(

**Comment by phonicmouse** [comment]
Oh...I'm really sorry, dont worry about that, if you're too busy don't mind.

**Comment by phonicmouse** [comment]
closing due to long inactivity. if you have news just write a new comment
