### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by worldworm** [phonicmouse/SharpPaste#113]
Does this page relates to your project?
https://sharppaste.nl/
It is not available.

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by worldworm** [comment]
ping @phonicmouse

**Comment by phonicmouse** [comment]
Hi @worldworm. The site is not active anymore. 
We've stopped support for a demo due to really low traffic.
There is no plan in the short-term to offer a demo site.

**Comment by worldworm** [comment]
Unfortunately this site was removed from awesome-selfhosted due to inactivity. You can add this site at any time should it become active again.
Thanks for your understanding!

https://github.com/awesome-selfhosted/awesome-selfhosted
https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1767
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1838
