### ISSUE TITLE
Tag new version 

### ISSUE THREAD

**Issue by tenchooo** [phonicmouse/SharpPaste#83]
We should release a basic version with basic functionalities tagged as 2.0.0-beta since we are still developing but it is the new rewrite of the app.
@phonicmouse It would be actually the release you're using on https://sharppaste.nl
If possible it should be a good idea to release precompiled version.

**Comment by phonicmouse** [comment]
Ok, i like the idea, proceed.
tag @2.0.0-beta

**Comment by tenchooo** [comment]
Ok
